apiVersion: v1
kind: ConfigMap
metadata:
  name: doc-router-config
  namespace: doc-router
data:
  ENV: "test"
  FASTAPI_BACKEND_URL: "http://backend.doc-router.svc.cluster.local:8000"
  FASTAPI_ROOT_PATH: "/"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXT_PUBLIC_FASTAPI_FRONTEND_URL: "http://localhost:8000"
  N_WORKERS: "4"
