apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doc-router

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - mongodb/statefulset.yaml
  - mongodb/service.yaml
  - mongodb/pvc.yaml

commonLabels:
  app.kubernetes.io/name: doc-router
  app.kubernetes.io/part-of: doc-router
