name: Frontend Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'packages/typescript/frontend/**'
      - 'packages/typescript/sdk/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'packages/typescript/frontend/**'
      - 'packages/typescript/sdk/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Build SDK
      run: npm ci && npm run build
      working-directory: ./packages/typescript/sdk

    - name: Install dependencies
      run: npm ci
      working-directory: ./packages/typescript/frontend

    - name: Build
      run: npm run build
      working-directory: ./packages/typescript/frontend
      env:
        NEXT_PUBLIC_FASTAPI_FRONTEND_URL: 'http://localhost:8000'
      timeout-minutes: 15 